### ISSUE TITLE
Add support for other devices from the gd32-rs PAC

### ISSUE THREAD

**Issue by kaizensparc** [gd32-rust/gd32f1x0-hal#27]
Hi!
I'm currently implementing support for the GD32E103 MCU in rust. A first part of the PAC is available on gd32-rs and I was planning on starting writing the HAL now. Is this crate a good place to add support for other GD32 devices HAL, or is the goal of this HAL only to support GD32F1x0 devices?

Thanks,

**Comment by qwandor** [comment]
Hello again!
This HAL crate is only intended to support GD32F1x0 devices. I suggest starting a new crate for the GD32E103, though if there's enough in common it might make sense to start it as a fork of this crate. I'm happy to make you a repository in the https://github.com/gd32-rust/ organisation for it if you like. This is consistent with the approach the https://github.com/stm32-rs/ organisation has taken for STM32 HAL crates, though it does mean some code duplication. I don't have a great solution for that. My concern with putting everything in the same crate is that it would just result in an unreadable mess of `#[cfg]` directives.

**Comment by kaizensparc** [comment]
Perfect, thanks :)
