### ISSUE TITLE
Delay example is not working on GD32F130G6 and GD32F130G8

### ISSUE THREAD

**Issue by Serhii-the-Dev** [gd32-rust/gd32f1x0-hal#50]
I was trying to understand how the system clock abstraction is working in scope of implementation of the #49 and found that the `delay` example is actually not working with the specified values (i.e. `delay.delay_ms(1_000)`), the LED pin is just keeping the high logic state. However, when setting the delay to some extreme value, like 10_000_000, the LED starts blinking although there is no clear correlation between the value and blinking speed. I checked it on both a dev board (some sort of a Blue Pill clone) with a GD32F130G6 and a custom board with GD32F130G8.

**Comment by Serhii-the-Dev** [comment]
Just an update: tweaking the `hclk` to some extremely low values on a scale of a few Hz the delay may be narrowed to an expected result though it doesn't seems right. The whole sample I'm using just for the reference:
```rust
#![deny(unsafe_code)]
#![no_main]
#![no_std]

use panic_halt as _;

use cortex_m_rt::entry;
use embedded_hal::{
    delay::DelayNs,
    digital::OutputPin,
};
use gd32f1x0_hal::{
    delay::Delay,
    pac,
    prelude::*,
};

#[entry]
fn main() -> ! {
    let cp = cortex_m::Peripherals::take().unwrap();
    let dp = pac::Peripherals::take().unwrap();

    let mut rcu = dp.rcu.constrain();
    let mut flash = dp.fmc.constrain();

    let clocks = rcu.cfgr.freeze(&mut flash.ws);

    let mut gpioa = dp.gpioa.split(&mut rcu.ahb);

    let mut led_red = gpioa.pa4.into_push_pull_output(&mut gpioa.config);
    let mut led_blue = gpioa.pa3.into_push_pull_output(&mut gpioa.config);
    let mut led_white = gpioa.pa2.into_push_pull_output(&mut gpioa.config);

    let mut delay = Delay::new(cp.SYST, clocks);

    led_red.set_high().unwrap();
    led_blue.set_high().unwrap();
    led_white.set_high().unwrap();

    loop {
        led_red.set_low().unwrap();
        led_blue.set_high().unwrap();
        delay.delay_ms(1000);
        led_red.set_high().unwrap();
        led_blue.set_low().unwrap();
        delay.delay_ms(1000);
    }
}

```

**Comment by qwandor** [comment]
I suspect this is due to integer overflow in the calculation of the total ticks in https://github.com/gd32-rust/gd32f1x0-hal/blob/main/src/delay.rs#L37. We should use a `u64` for the intermediate value, as https://github.com/nrf-rs/nrf-hal/blob/master/nrf-hal-common/src/delay.rs#L75 does.

**Comment by qwandor** [comment]
Can you check if #51 fixes the issue?

**Comment by Serhii-the-Dev** [comment]
Hi!
#51 works great! I applied the patch from your commit:
```toml
[patch.crates-io]
gd32f1x0-hal = { git = "https://github.com/gd32-rust/gd32f1x0-hal", rev = "58c3594809d9869070d312f1f7de1f24ff4b22e2" }
```
And the timings are correct now, at least visually...I don't have any precise tools to measure them on µs level anyway :)

https://github.com/gd32-rust/gd32f1x0-hal/assets/2578826/f4d39653-1b25-423a-9a7c-30d8fb1c5357

This board also includes a 8Mhz oscillator so I checked the `hxtal` clock config which also works great with the fix.

**Comment by qwandor** [comment]
Actually I've pushed 0.10.1 now with this fix.
